algoritmo "circulo"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Matheus Nascimento de Araujp
// Data atual  : 29/08/2005
var
    raio, area :real

inicio
    escreva ("Escreva o raio do circulo: ")
    leia (raio)
    area <- pi * (raio * raio)
    escreva ("A area do seu circulo é: ", area)

fimalgoritmo