algoritmo "Nome do Programa"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Matheus Nascimento de Araujo
// Data atual  : 03/09/2025
var

    temp_fh, temp_cls :real

inicio

    escreval ("Digite a temperatra em celsius: ")
    leia (temp_cls)
    temp_fh <- (temp_cls * 9/5) + 32
    escreval ("A temperatura de ", temp_cls, "ºC é igual a: ", temp_fh)

fimalgoritmo