algoritmo "positivo_negativo"
// Disciplina  : [Lógica de Programação]
// Professor   : Jaislon Costa dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Matheus Nascimento de Araujo
// Data atual  : 03/09/2025
var

    n1 :inteiro

inicio

    escreval ("Digite um número: ")
    leia (n1)

    se (n1 < 0) entao
        escreva ("Seu número é negativo")
    senao
        escreva ("Seu número é positivo")
    fimse


fimalgoritmo