algoritmo "Nome do Programa"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Matheus Nascimento de Araujo
// Data atual  : 03/09/2025
var

    temp_fh, temp_cls :real

inicio

    escreval ("Digite a temperatra em fahrenheit: ")
    leia (temp_fh)
    temp_cls <- (temp_fh - 32) * 5/9
    escreval ("A temperatura de ", temp_fh, "ºF é igual a: ", temp_cls)

fimalgoritmo