algoritmo "multiplicacao"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Matheus Nascimento de Araujp
// Data atual  : 29/08/2005
var
    n1, n2, mult :inteiro

inicio

    escreva ("Digite o primeiro número: ")
    leia (n1)
    escreva ("Digite o segundo número")
    leia (n2)
    mult <- n1 * n2
    escreva("A multiplicação dos dois números é: ", mult)

fimalgoritmo