algoritmo "quadrado"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Matheus Nascimento de Araujp
// Data atual  : 29/08/2005
var
    alt, area :real

inicio

    escreva ("Digite a altura do quadrado: ")
    leia (alt)
    area <- alt^2
    escreva ("A area do seu quadrado é", area)


fimalgoritmo