algoritmo "soma"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Matheus Nascimento de Araujp
// Data atual  : 29/08/2005
var
    n1, n2, soma :inteiro

inicio

    escreva ("Digite o primeiro número: ")
    leia (n1)
    escreva ("Digite o segundo número")
    leia (n2)
    soma <- n1 + n2
    escreva("A soma dos dois números é: ", soma)

fimalgoritmo