algoritmo "subtracao"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Matheus Nascimento de Araujp
// Data atual  : 29/08/2005
var
    n1, n2, sub :inteiro

inicio

    escreva ("Digite o primeiro número: ")
    leia (n1)
    escreva ("Digite o segundo número")
    leia (n2)
    sub <- n1 - n2
    escreva("A subtração dos dois números é: ", sub)

fimalgoritmo